<?php /** This PHP File is auto-generated from theme option. Please do not edit this file directly**/ ?>
<?php
##Start your code below this line
add_action('my_action','my_function');
function my_function() {
	echo 'Hello';
}