/** This Javascript File is auto-generated from theme option. Please do not edit this file directly**/
'use strict';
( function($) {
	$('.genesis-nav-menu').cmknav({
		label: '<i class="fa fa-navicon"></i>',
	});//This code is required for Mobile Menu
	//Start your code below this line
	
})(jQuery);